[23/Jun/2017 14:46:39] INFO [django.server:124] "GET /login/ HTTP/1.1" 200 4595
[23/Jun/2017 14:46:39] INFO [django.server:124] "GET /static/img/favicon-32x32.d59b1d998588.png HTTP/1.1" 200 2022
[23/Jun/2017 16:11:22] ERROR [django.request:135] Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/forgeguest/Documents/better_getter/accounts/views.py", line 41, in login
    login_form = AuthenticationForm(request)
NameError: global name 'AuthenticationForm' is not defined
[23/Jun/2017 16:11:22] ERROR [django.server:124] "GET /login/ HTTP/1.1" 500 27
[23/Jun/2017 16:11:38] ERROR [django.request:135] Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/forgeguest/Documents/better_getter/accounts/views.py", line 41, in login
    login_form = AuthenticationForm(request)
NameError: global name 'AuthenticationForm' is not defined
[23/Jun/2017 16:11:38] ERROR [django.server:124] "GET /login/ HTTP/1.1" 500 27
[23/Jun/2017 16:11:43] ERROR [django.request:135] Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/forgeguest/Documents/better_getter/accounts/views.py", line 41, in login
    login_form = AuthenticationForm(request)
NameError: global name 'AuthenticationForm' is not defined
[23/Jun/2017 16:11:43] ERROR [django.server:124] "GET /login/ HTTP/1.1" 500 27
[23/Jun/2017 16:12:42] DEBUG [django.template:925] Exception while resolving variable 'form' in template 'login.html'.
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa51d63ff50>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa51d8df2a8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa51c5d9890>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa51d894e90>, u\'request\': <WSGIRequest: GET \'/login/\'>}, {}, {\'login_form\': <AuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'signup_form\': <CreateUserForm bound=False, valid=Unknown, fields=(username;password1;password2)>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n<div class="container">\'>, <IfNode>, <TextNode: u\'\\n              <form acti\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa51d64d450>, <TextNode: u\'\\n\\n                <h2>LOG\'>, <For Node: for field in login_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>, <For Node: for field in signup_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>]>}]'
[23/Jun/2017 16:12:42] INFO [django.server:124] "GET /login/ HTTP/1.1" 200 6675
[23/Jun/2017 16:12:43] INFO [django.server:124] "GET /static/css/auth.a246e82b885c.css HTTP/1.1" 200 1304
[23/Jun/2017 16:12:43] INFO [django.server:124] "GET /static/img/favicon-32x32.d59b1d998588.png HTTP/1.1" 200 2022
[23/Jun/2017 16:13:22] DEBUG [django.template:925] Exception while resolving variable 'form' in template 'login.html'.
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa51c60c668>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa51c60c5f0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa51c5c4a50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa51c5c4090>, u\'request\': <WSGIRequest: GET \'/login/\'>}, {}, {\'login_form\': <AuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'signup_form\': <CreateUserForm bound=False, valid=Unknown, fields=(username;password1;password2)>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n<div class="container">\'>, <IfNode>, <TextNode: u\'\\n              <form acti\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa51d64d450>, <TextNode: u\'\\n\\n                <h2>LOG\'>, <For Node: for field in login_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>, <For Node: for field in signup_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>]>}]'
[23/Jun/2017 16:13:22] INFO [django.server:124] "GET /login/ HTTP/1.1" 200 6675
[23/Jun/2017 16:13:26] INFO [django.server:124] "GET /static/img/favicon-32x32.d59b1d998588.png HTTP/1.1" 200 2022
[23/Jun/2017 16:13:31] DEBUG [django.template:925] Exception while resolving variable 'form' in template 'login.html'.
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa51c60cde8>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa51c60c668>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa51c5d64d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa51c5c4d10>, u\'request\': <WSGIRequest: GET \'/login/\'>}, {}, {\'login_form\': <AuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'signup_form\': <CreateUserForm bound=False, valid=Unknown, fields=(username;password1;password2)>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n<div class="container">\'>, <IfNode>, <TextNode: u\'\\n              <form acti\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa51d64d450>, <TextNode: u\'\\n\\n                <h2>LOG\'>, <For Node: for field in login_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>, <For Node: for field in signup_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>]>}]'
[23/Jun/2017 16:13:31] INFO [django.server:124] "GET /login/ HTTP/1.1" 200 6675
[23/Jun/2017 16:13:32] INFO [django.server:124] "GET /static/img/favicon-32x32.d59b1d998588.png HTTP/1.1" 200 2022
[23/Jun/2017 16:13:45] INFO [django.server:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 99165
[23/Jun/2017 16:14:32] DEBUG [django.template:925] Exception while resolving variable 'form' in template 'login.html'.
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa51c60cb90>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa51c60cde8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa51c5d6810>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa51d894490>, u\'request\': <WSGIRequest: GET \'/login/\'>}, {}, {\'login_form\': <AuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'signup_form\': <CreateUserForm bound=False, valid=Unknown, fields=(username;password1;password2)>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n<div class="container">\'>, <IfNode>, <TextNode: u\'\\n              <form acti\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa51d64d450>, <TextNode: u\'\\n\\n                <h2>LOG\'>, <For Node: for field in login_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>, <For Node: for field in signup_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>]>}]'
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /login/ HTTP/1.1" 200 6675
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/css/typeaheadjs.74cbdb0b28ef.css HTTP/1.1" 200 685
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/css/auth.a246e82b885c.css HTTP/1.1" 200 1304
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/css/common.8762ac3c6160.css HTTP/1.1" 200 1135
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/css/bootstrap.min.1825bc9de3d6.css HTTP/1.1" 200 19644
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/mmenu/jquery.mmenu.all.9e950209fa6b.css HTTP/1.1" 200 6658
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/mmenu/wrappers/bootstrap/jquery.mmenu.bootstrap.d0a03cbdb1ba.css HTTP/1.1" 200 150
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/js/hammer.min.150659814972.js HTTP/1.1" 200 7341
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/js/jquery.min.4f252523d4af.js HTTP/1.1" 200 33738
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/js/bootstrap.min.5869c96cc8f1.js HTTP/1.1" 200 9806
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/js/search.7d707a66c25f.js HTTP/1.1" 200 9786
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/js/typeahead.fd054c48bcd9.js HTTP/1.1" 200 11583
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/mmenu/wrappers/bootstrap/jquery.mmenu.bootstrap.213ae8f5d26d.js HTTP/1.1" 200 743
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/mmenu/jquery.mmenu.all.28049b64fb08.js HTTP/1.1" 200 15166
[23/Jun/2017 16:14:32] INFO [django.server:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 99165
[23/Jun/2017 16:14:33] INFO [django.server:124] "GET /static/fonts/glyphicons-halflings-regular.448c34a56d69.woff2 HTTP/1.1" 200 18028
[23/Jun/2017 16:14:33] WARNING [django.request:152] Not Found: /static/js/hammer.min.js.map
[23/Jun/2017 16:14:33] WARNING [django.server:124] "GET /static/js/hammer.min.js.map HTTP/1.1" 404 101
[23/Jun/2017 16:14:59] DEBUG [django.template:925] Exception while resolving variable 'form' in template 'login.html'.
Traceback (most recent call last):
  File "/home/forgeguest/Documents/better_getter/.venv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe5ad19ef50>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe5ad43c2a8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe5ac938590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe5ad3f1b90>, u\'request\': <WSGIRequest: GET \'/login/\'>}, {}, {\'login_form\': <AuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'signup_form\': <CreateUserForm bound=False, valid=Unknown, fields=(username;password1;password2)>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n<div class="container">\'>, <IfNode>, <TextNode: u\'\\n\\n              <form id=\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe5ad1ad150>, <TextNode: u\'\\n\\n                <h2>LOG\'>, <For Node: for field in login_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>, <For Node: for field in signup_form, tail_len: 5>, <TextNode: u\'\\n\\n                  <div \'>]>}]'
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /login/ HTTP/1.1" 200 6161
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/css/bootstrap.min.1825bc9de3d6.css HTTP/1.1" 200 19644
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/css/typeaheadjs.74cbdb0b28ef.css HTTP/1.1" 200 685
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/mmenu/jquery.mmenu.all.9e950209fa6b.css HTTP/1.1" 200 6658
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/mmenu/wrappers/bootstrap/jquery.mmenu.bootstrap.d0a03cbdb1ba.css HTTP/1.1" 200 150
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/css/common.8762ac3c6160.css HTTP/1.1" 200 1135
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/css/auth.2fb07ada9774.css HTTP/1.1" 200 1291
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/js/hammer.min.150659814972.js HTTP/1.1" 200 7341
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/js/jquery.min.4f252523d4af.js HTTP/1.1" 200 33738
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/js/bootstrap.min.5869c96cc8f1.js HTTP/1.1" 200 9806
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/js/typeahead.fd054c48bcd9.js HTTP/1.1" 200 11583
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/js/search.7d707a66c25f.js HTTP/1.1" 200 9786
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/mmenu/jquery.mmenu.all.28049b64fb08.js HTTP/1.1" 200 15166
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/mmenu/wrappers/bootstrap/jquery.mmenu.bootstrap.213ae8f5d26d.js HTTP/1.1" 200 743
[23/Jun/2017 16:14:59] INFO [django.server:124] "GET /static/fonts/glyphicons-halflings-regular.448c34a56d69.woff2 HTTP/1.1" 200 18028
[23/Jun/2017 16:15:00] WARNING [django.request:152] Not Found: /static/js/hammer.min.js.map
[23/Jun/2017 16:15:00] WARNING [django.server:124] "GET /static/js/hammer.min.js.map HTTP/1.1" 404 101
[23/Jun/2017 16:15:00] INFO [django.server:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 99165
